import PDFDocument from "pdfkit";

type AnyObj = Record<string, any>;

const safeText = (v: any): string => {
  if (v === null || v === undefined) return "N/A";
  const s = String(v).trim();
  return s.length ? s : "N/A";
};

const fmtInt = (v: any): string => {
  const n = Number(v);
  if (!Number.isFinite(n)) return "0";
  return String(Math.round(n));
};

const fmtNumber = (v: any, digits = 2): string => {
  const n = Number(v);
  if (!Number.isFinite(n)) return "0";
  return n.toFixed(digits);
};

const fmtCurrency = (v: any): string => {
  const n = Number(v);
  if (!Number.isFinite(n)) return "0.00";
  return n.toFixed(2);
};

function ensureObject(v: any): any {
  if (typeof v === "string") {
    try { return JSON.parse(v); } catch { return v; }
  }
  return v;
}

function pageBreakIfNeeded(doc: typeof PDFDocument, minSpace = 80) {
  if ((doc as any).y > 792 - minSpace) doc.addPage();
}

export function generateSalesAnalysisReportPdf(reportEntity: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50 });
      const buffers: Buffer[] = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", reject);

      const rep: AnyObj = reportEntity ?? {};
      rep.parametri = ensureObject(rep.parametri);
      rep.rezultat = ensureObject(rep.rezultat);

      const id = safeText(rep.id);
      const createdAt = rep.datumKreiranja ? new Date(rep.datumKreiranja) : null;
      const createdAtStr = createdAt ? createdAt.toLocaleString() : "N/A";

      const rezultat: AnyObj = rep.rezultat ?? {};
      const meta: AnyObj = rezultat.meta ?? {};
      const kpis: AnyObj = rezultat.kpis ?? {};
      const trend: AnyObj[] = Array.isArray(rezultat.trend) ? rezultat.trend : [];
      const top10: AnyObj[] = Array.isArray(rezultat.top10) ? rezultat.top10 : [];

      doc.fontSize(20).text("Sales Analysis Report", { align: "center" });
      doc.moveDown(0.4);
      doc.fontSize(10).text("Parfimerija O'Sinel De Or", { align: "center" });
      doc.moveDown(1.2);

      doc.fontSize(12).text("Report Details", { underline: true });
      doc.moveDown(0.6);

      doc.fontSize(11).text(`Report ID: ${id}`);
      doc.text(`Type: ${safeText(rep.tipIzvestaja)}`);
      doc.text(`Created at: ${createdAtStr}`);
      doc.text(`Period: from ${safeText(meta.from)} to ${safeText(meta.to)} (groupBy: ${safeText(meta.groupBy)})`);
      doc.moveDown(1.2);

      doc.fontSize(12).text("KPIs", { underline: true });
      doc.moveDown(0.6);

      doc.fontSize(11).text(`Total revenue: ${fmtCurrency(kpis.totalRevenue)}`);
      doc.text(`Total receipts: ${fmtInt(kpis.totalReceipts)}`);
      doc.text(`Total sold (all): ${fmtInt(kpis.totalSoldAll)}`);
      doc.text(`Avg daily sold: ${fmtNumber(kpis.avgDailySold, 2)}`);

      const bestDay = kpis.bestDay;
      if (bestDay) {
        doc.text(`Best day: ${safeText(bestDay.date)} (qty: ${fmtInt(bestDay.qty)})`);
      } else {
        doc.text(`Best day: N/A`);
      }

      doc.moveDown(1.2);

      doc.fontSize(12).text("Trend", { underline: true });
      doc.moveDown(0.6);

      doc.fontSize(10);
      doc.text("Period", 50, (doc as any).y, { continued: true });
      doc.text("Qty", 250, (doc as any).y, { continued: true });
      doc.text("Revenue", 330, (doc as any).y);
      doc.moveDown(0.3);

      for (const row of trend) {
        pageBreakIfNeeded(doc, 60);
        doc.text(safeText(row.t), 50, (doc as any).y, { continued: true });
        doc.text(fmtInt(row.kolicina), 250, (doc as any).y, { continued: true });
        doc.text(fmtCurrency(row.prihod), 330, (doc as any).y);
      }

      doc.moveDown(1.2);

      doc.fontSize(12).text("Top 10 by Revenue", { underline: true });
      doc.moveDown(0.6);

      doc.fontSize(10);
      doc.text("Perfume", 50, (doc as any).y, { continued: true });
      doc.text("Qty", 300, (doc as any).y, { continued: true });
      doc.text("Revenue", 380, (doc as any).y);
      doc.moveDown(0.3);

      for (const row of top10) {
        pageBreakIfNeeded(doc, 60);
        doc.text(safeText(row.naziv), 50, (doc as any).y, { continued: true });
        doc.text(fmtInt(row.kolicina), 300, (doc as any).y, { continued: true });
        doc.text(fmtCurrency(row.prihod), 380, (doc as any).y);
      }

      doc.moveDown(1.4);
      doc.fontSize(9).text("Generated by Analysis Microservice", { align: "center" });

      doc.end();
    } catch (e) {
      reject(e);
    }
  });
}
